----注意，除了字符串不能包含任何其它数据结构，比如table
--扩展UI配置，在此处添加的界面资源可以不用再ECResPath.lua里面注册

local EXTEND_RESPATH = 
{
	SubPanel_Money_Tree = "Arts/Res/Prefab/SubPanel_Money_Tree.prefab.u3dext",
	SubPanel_Love_Rank = "Arts/Res/Prefab/SubPanel_Love_Rank.prefab.u3dext",
	SubPanel_FoolsDay = "Arts/Res/Prefab/SubPanel_FoolsDay.prefab.u3dext",
	SubPanel_Anniversary = "Arts/Res/Prefab/SubPanel_Anniversary.prefab.u3dext",
	SubPanel_ImpossibleGame = "Arts/Res/Prefab/SubPanel_ImpossibleGame.prefab.u3dext",
	SubPanel_ImpossibleGame2 = "Arts/Res/Prefab/SubPanel_ImpossibleGame2.prefab.u3dext",
	SubPanel_NewProActivity = "Arts/Res/Prefab/SubPanel_NewProActivity.prefab.u3dext",
	SubPanel_Blessing = "Arts/Res/Prefab/SubPanel_Blessing.prefab.u3dext",
	SubPanel_ChildrenDay03 = "Arts/Res/Prefab/SubPanel_ChildrenDay03.prefab.u3dext",
	SubPanel_EuropeanCup2 = "Arts/Res/Prefab/SubPanel_EuropeanCup2.prefab.u3dext",
	SubPanel_EuropeanCup3 = "Arts/Res/Prefab/SubPanel_EuropeanCup3.prefab.u3dext",
	SubPanel_EuropeanCup4 = "Arts/Res/Prefab/SubPanel_EuropeanCup4.prefab.u3dext",
	SubPanel_Server_Boss1 = "Arts/Res/Prefab/SubPanel_Server_Boss1.prefab.u3dext",
	SubPanel_Server_Boss2 = "Arts/Res/Prefab/SubPanel_Server_Boss2.prefab.u3dext",
	SubPanel_Server_Boss3 = "Arts/Res/Prefab/SubPanel_Server_Boss3.prefab.u3dext",
	SubPanel_DoubleExp = "Arts/Res/Prefab/SubPanel_DoubleExp.prefab.u3dext",
	SubPanel_Love = "Arts/Res/Prefab/SubPanel_Love.prefab.u3dext",
	SubPanel_NewPvPActivity02 = "Arts/Res/Prefab/SubPanel_NewPvPActivity02.prefab.u3dext",
	SubPanel_OlympicGame2 = "Arts/Res/Prefab/SubPanel_OlympicGame2.prefab.u3dext",
	SubPanel_NationTransfer = "Arts/Res/Prefab/SubPanel_NationTransfer.prefab.u3dext",
	SubPanel_Onsale = "Arts/Res/Prefab/SubPanel_Onsale.prefab.u3dext",
	SubPanel_Area = "Arts/Res/Prefab/SubPanel_Area.prefab.u3dext",
	SubPanel_National_Car = "Arts/Res/Prefab/SubPanel_National_Car.prefab.u3dext",
	SubPanel_Backguoqing = "Arts/Res/Prefab/SubPanel_Backguoqing.prefab.u3dext",
	SubPanel_Backguoqing3Day = "Arts/Res/Prefab/SubPanel_Backguoqing3Day.prefab.u3dext",
	SubPanel_Guang11 = "Arts/Res/Prefab/SubPanel_Guang11.prefab.u3dext",
	SubPanel_ThanksgivingDay = "Arts/Res/Prefab/SubPanel_ThanksgivingDay.prefab.u3dext",
	SubPanel_ThanksDay = "Arts/Res/Prefab/SubPanel_ThanksDay.prefab.u3dext",
	SubPanel_MagicBox = "Arts/Res/Prefab/SubPanel_MagicBox.prefab.u3dext",
	SubPanel_Rift = "Arts/Res/Prefab/SubPanel_Rift.prefab.u3dext",
	Subpanel_MonsterAttack = "Arts/Res/Prefab/Subpanel_MonsterAttack.prefab.u3dext",
	SubPanel_SDJ = "Arts/Res/Prefab/SubPanel_SDJ.prefab.u3dext",
	SubPanel_YDJ_explain = "Arts/Res/Prefab/SubPanel_YDJ_explain.prefab.u3dext",
	SubPanel_YDJ_Boss = "Arts/Res/Prefab/SubPanel_YDJ_Boss.prefab.u3dext",
	SubPanel_XmasSell = "Arts/Res/Prefab/SubPanel_XmasSell.prefab.u3dext",
	SubPanel_XmasRecharge = "Arts/Res/Prefab/SubPanel_XmasRecharge.prefab.u3dext",
	SubPanel_LaBaShouLie = "Arts/Res/Prefab/SubPanel_LaBaShouLie.prefab.u3dext",
	SubPanel_LaBaHaoLi = "Arts/Res/Prefab/SubPanel_LaBaHaoLi.prefab.u3dext",
	SubPanel_Spring_Hero1 = "Arts/Res/Prefab/SubPanel_Spring_Hero1.prefab.u3dext",  --重新关联新春界面
	SubPanel_Chunjie = "Arts/Res/Prefab/SubPanel_Chunjie.prefab.u3dext",
	SubPanel_ChunJie3Day = "Arts/Res/Prefab/SubPanel_ChunJie3Day.prefab.u3dext",
	SubPanel_YearRedBag = "Arts/Res/Prefab/SubPanel_YearRedBag.prefab.u3dext",
	SubPanel_TaskQuest= "Arts/Res/Prefab/SubPanel_TaskQuest.prefab.u3dext",	
	SubPanel_Nanmanruqin= "Arts/Res/Prefab/SubPanel_Nanmanruqin.prefab.u3dext",
	SubPanel_SouthInvade= "Arts/Res/Prefab/SubPanel_SouthInvade.prefab.u3dext",
	SubPanel_Zhishujie= "Arts/Res/Prefab/SubPanel_Zhishujie.prefab.u3dext",
	SubPanel_MonthLove = "Arts/Res/Prefab/SubPanel_MonthLove.prefab.u3dext",
	SubPanel_ChaseSoul = "Arts/Res/Prefab/SubPanel_ChaseSoul.prefab.u3dext",
	SubPanel_QMJ_everyday = "Arts/Res/Prefab/SubPanel_QMJ_everyday.prefab.u3dext",
	SubPanel_4_Spirit_Intro_Qinglong= "Arts/Res/Prefab/SubPanel_4_Spirit_Intro_Qinglong.prefab.u3dext",
	SubPanel_4_Spirit_Intro_Zhuque= "Arts/Res/Prefab/SubPanel_4_Spirit_Intro_Zhuque.prefab.u3dext",
	SubPanel_4_Spirit_Intro_Baihu= "Arts/Res/Prefab/SubPanel_4_Spirit_Intro_Baihu.prefab.u3dext",
	SubPanel_4_Spirit_Intro_Xuanwu= "Arts/Res/Prefab/SubPanel_4_Spirit_Intro_Xuanwu.prefab.u3dext",
	SubPanel_HefuBuchang= "Arts/Res/Prefab/SubPanel_HefuBuchang.prefab.u3dext",
	SubPanel_Camp= "Arts/Res/Prefab/SubPanel_Camp.prefab.u3dext",
	SubPanel_ThemeWeek="Arts/Res/Prefab/SubPanel_ThemeWeek.prefab.u3dext",
	SubPanel_AllPlayer="Arts/Res/Prefab/SubPanel_AllPlayer.prefab.u3dext",
	SubPanel_DragonBall="Arts/Res/Prefab/SubPanel_DragonBall.prefab.u3dext",
	SubPanel_4_Spirit_Together= "Arts/Res/Prefab/SubPanel_4_Spirit_Together.prefab.u3dext",
	SubPanel_GuoLiZhengBa= "Arts/Res/Prefab/SubPanel_GuoLiZhengBa.prefab.u3dext",
	Subpanel_Halloween = "Arts/Res/Prefab/Subpanel_Halloween.prefab.u3dext",
	SubPanel_Server_Camp= "Arts/Res/Prefab/SubPanel_Server_Camp.prefab.u3dext",
	SubPanel_GuessNum= "Arts/Res/Prefab/SubPanel_GuessNum.prefab.u3dext",
	SubPanel_SizeQuit="Arts/Res/Prefab/SubPanel_SizeQuit.prefab.u3dext",
	SubPanel_RankingShowC="Arts/Res/Prefab/SubPanel_RankingShowC.prefab.u3dext",
	SubPanel_RankingShowM="Arts/Res/Prefab/SubPanel_RankingShowM.prefab.u3dext",
	SubPanel_RankingShowZ="Arts/Res/Prefab/SubPanel_RankingShowZ.prefab.u3dext",
	SubPanel_QMJ_task="Arts/Res/Prefab/SubPanel_QMJ_task.prefab.u3dext",
	SubPanel_Qixi_Des="Arts/Res/Prefab/SubPanel_Qixi_Des.prefab.u3dext",
	SubPanel_Qixi_Rew="Arts/Res/Prefab/SubPanel_Qixi_Rew.prefab.u3dext",
	SubPanel_FourSwords="Arts/Res/Prefab/SubPanel_FourSwords.prefab.u3dext",
	SubPanel_TeachersDay="Arts/Res/Prefab/SubPanel_TeachersDay.prefab.u3dext", 
	SubPanel_TeachersDay_Daily="Arts/Res/Prefab/SubPanel_TeachersDay_Daily.prefab.u3dext", 
	SubPanel_DoubleEleven_Des="Arts/Res/Prefab/SubPanel_DoubleElevenDes.prefab.u3dext", 
	SubPanel_DoubleEleven_Sign="Arts/Res/Prefab/SubPanel_DoubleElevenSign.prefab.u3dext", 
	SubPanel_DoubleEleven_Rew="Arts/Res/Prefab/SubPanel_DoubleElevenRew.prefab.u3dext", 
	SubPanel_Horse_Race="Arts/Res/Prefab/SubPanel_Horse_Race.prefab.u3dext",
	SubPanel_Yanwu_Explain="Arts/Res/Prefab/SubPanel_Yanwu_Explain.prefab.u3dext",
	SubPanel_Server_Camp2="Arts/Res/Prefab/SubPanel_Server_Camp2.prefab.u3dext",
}


return EXTEND_RESPATH