[Identify]
;这个是gs的id需要在gsalias覆盖掉保证每个gs的id不同
ServerID		= 255

[SpawnController]
;disable			= 12345 54321

[General]
;所有开放的场景
all_scenes		= 5002;5003;5004;5005;5006;

;本线支持的世界
worlds			= 0;

;是否防沉迷
anti_wallow		= true
;调试命令
debug_command_mode	= 1
CheckPlayerMove         = 1

;逻辑级别限制
logic_level_limit = 90
;允许登入职业 0xffffffff = 4294967295
allow_login_prof_mask = 31
;禁止输出
no_output = 0
no_skoutput = 1
vip_system_open = 1
;是否开启严格的移动时间戳校验
open_move_check		= 1

[WallowLight]
exp			= 0.5f
sp			= 0.5f
item			= 0.5f
money			= 0.5f
task_exp		= 0.5f
task_sp			= 0.5f
task_money		= 0.5f

[WallowHeavy]
exp			= 0
sp			= 0
item			= 0
money			= 0
task_exp		= 0
task_sp			= 0
task_money		= 0

[WallowTime]
TimeLight		= 10
TimeHeavy		= 20
TimeClear		= 15
ClearMode		= RestTime

[Param]
;未使用,这种参数配置应该在world层配置
;forbid_trade		= 0
;是否允许root启动程序
allow_root		= 1

[MoveMap]
Path			= movemap
WaterPath		= watermap
AirPath			= airmap
FieldPath               = movemap/field.map
GenField                = false

[Script]
;注意要用绝对路径
GlobalScript		= ./config/script/global_script.lua

[Template]
;注意要用绝对路径,目录名字后面加"/"
Root			= ./config/
aiscript_root		= aiscript/
item_data_file		= server/elements.data
addon_type		= server/addon.txt
reinforce_tab		= server/enhancetab.txt
elixir_tab		= server/elixirtab.txt
prof_lvup		= server/proftab.txt
tid_lvup		= server/tidtab.txt
task_data_file		= tasks.data
dyn_task_data_file	= dyn_tasks.data
mall_data_file		= server/malldata.xml
policy_data_file	= policy.data
DropData		= extra_drops.sev
LuaData			= global_api.lua
atkdefmodi		= AtkDefModi.txt
map_conf_file		= terrain.cfg
force_data		= Exp2Force.txt
skills_data		= skills.data
skill_combo		= server/series-skill_cancel.txt
skill_limit		= server/pre-skill_limit.txt
level_difficulty	= server/level_difficulty.txt
level_treasure		= server/level_treasure.txt
level_score		= server/level_score.txt
doll_config_file	= server/doll_summon_configs.txt
practice_file		= server/practice.txt
teleport_file		= server/teleport.txt
reward_file		= server/reward_item.txt
stagedata		= server/StageData.xml
sweepreward		= server/sweep.txt
equipment_suit_table    = server/equipment_suit_table.txt

RestartShell		= ./restart

RegionFile		= region.sev
RegionFile2		= precinct.sev
RegionFile3		= bufregion.sev
NPCGenFile		= npcgen.data
PathFile		= path.sev

DiscovermapDef		= server/discover.txt
board_data		= boards.data

