--[[
	列举所有弹出界面 (用户通过简单步骤可打开的界面)
]]

--[[
	格式：
		界面名 = true,		--true 表示是一个弹出界面
		
	** 提示：可用大小写转换批量转成小写
]]
local popup_panel_list =
{
	panel_achievement = true,
	panel_activity_goodstransport = true,
	panel_addfriend = true,
	panel_arena = true,
	panel_arena_rank = true,
	panel_arena_shop = true,
	panel_auction = true,
	panel_auction_buy = true,
	panel_batchuse = true,
	panel_bobyshop = true,
	panel_bonus = true,
	panel_bonus_five = true,
	panel_bonus_one = true,
	panel_card =  true,
	panel_cardinfo = true,
	panel_cardresolve = true,
	panel_cg = true,
	panel_challengemain = true,
	panel_char = true,
	panel_chat = true,
	panel_charchoose = true,
	panel_chatfriend = true,
	panel_chatsetting = true,
	panel_commonreward = true,
	panel_communication = true,
	panel_continuousdraw = true,
	panel_donate_faction = true,
	panel_editaudio = true,
	panel_emotion = true,
	panel_equip_exterior = true,
	panel_equip_multirefresh = true,
	panel_equip_qualityup = true,
	panel_equip_underwear = true,
	panel_equipchoose = true,
	panel_faction = true,
	panel_faction_applylist = true,
	panel_faction_bonfire = true,
	panel_faction_donate = true,
	panel_factionannouncement = true,
	panel_factionbuild = true,
	panel_factioncreate = true,
	panel_factionhall = true,
	panel_factionmonster = true,
	panel_factionmonster_rank = true,
	panel_factionshop = true,
	panel_factionskill = true,
	panel_flower = true,
	panel_goldshop = true,
	panel_goldshop_buy = true,
	panel_goodstransport_confirm = true,
	panel_herald = true,
	panel_herofight = true,
	panel_instance_exp = true,
	panel_instance_money = true,
	panel_instance_story = true,
	panel_lottery = true,
	panel_lotteryout = true,
	panel_map_midmap = true,
	panel_mausoleum = true,
	panel_message = true,
	panel_nation = true,
	panel_nation_change = true,
	panel_nation_search = true,
	panel_national_war = true,
	panel_national_war_info = true,
	panel_national_waraccount = true,
	panel_nationannouncement = true,
	panel_nationboss = true,
	panel_npc = true,
	panel_npcquest = true,
	panel_npcshop = true,
	panel_npcshop_sell = true,
	panel_npcshopnum = true,
	panel_officer = true,
	panel_openreward = true,
	panel_option_chat = true,
	panel_option_faction = true,
	panel_option_friend = true,
	panel_option_other = true,
	panel_pass = true,
	panel_pass_shop = true,
	panel_plant = true,
	panel_pkmode = true,
	panel_popup = true,
	panel_quest = true,
	panel_quest_activitynew = true,
	panel_questseriesnew = true,
	panel_ranklist = true,
	panel_ride = true,
	panel_reward = true,
	panel_revivecharge = true,
	panel_ringquest = true,
	panel_setting = true,
	panel_skillmain = true,
	panel_stayoffline = true,
	panel_stayonline = true,
	panel_stayonlineget = true,
	panel_stayonlineout = true,
	panel_tallent = true,
	panel_transfer = true,
	panel_treebegin = true,
	panel_treeinfo = true,
	panel_vip = true,
	panel_watchother = true,
	panel_wedding = true,
	panel_wing = true,
	panel_retrieve = true,
	panel_elite = true,
	panel_fashionshop = true,
	panel_itemtip_fashion = true,
---------------------------------------------
	panel_inventory = true,
	panel_item_combine = true,
	panel_itemtip_equip = true,
	-- panel_itemtip_otheritem = true,
	panel_itemtip_skillstate = true,
	-- panel_menu = true,
	--panel_nextinfo = true,
	panel_quest_activity = true,
	-- panel_quicktips = true,
	panel_ridecolor = true,
	panel_social = true,
	panel_suit = true,
    panel_nation = true,
    panel_faction = true,
    panel_truefriend = ture,
    panel_qqright = ture,
}

return popup_panel_list
